# Generated by Django 6.0.5 on 2026-05-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0002_facility_order_trip_ticket_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_seat_trip",
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("seat", "trip"), name="unique_seat_trip"
            ),
        ),
    ]
