# Generated by Django 6.0.5 on 2026-05-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_remove_ticket_unique_seat_trip_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={"verbose_name_plural": "facilities"},
        ),
        migrations.AddField(
            model_name="bus",
            name="facilities",
            field=models.ManyToManyField(related_name="buses", to="station.facility"),
        ),
    ]
