# Generated by Django 6.0.5 on 2026-05-29 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0004_alter_facility_options_bus_facilities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="station.order",
            ),
        ),
    ]
