# Generated by Django 6.0.5 on 2026-05-30 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0005_alter_ticket_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("seat",)},
        ),
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_seat_trip",
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="station.trip",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("seat", "trip")},
        ),
    ]
