# Generated by Django 6.0.5 on 2026-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "station",
            "0006_alter_ticket_options_remove_ticket_unique_seat_trip_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
