# Generated by Django 6.0.5 on 2026-05-31 13:09

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0007_bus_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="image",
            field=models.ImageField(null=True, upload_to=station.models.bus_image_path),
        ),
    ]
