# Generated by Django 6.0.5 on 2026-05-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0008_alter_bus_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="facilities",
            field=models.ManyToManyField(
                blank=True, related_name="buses", to="station.facility"
            ),
        ),
    ]
